apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 822837196792.dkr.ecr.ap-northeast-2.amazonaws.com/ad1-ecr
  newName: 822837196792.dkr.ecr.ap-northeast-2.amazonaws.com/ad1-ecr
  newTag: f4f19b93
- name: 822837196792.dkr.ecr.ap-northeast-2.amazonaws.com/discount-ecr
  newName: 822837196792.dkr.ecr.ap-northeast-2.amazonaws.com/discount-ecr
  newTag: a5690044
- name: 822837196792.dkr.ecr.ap-northeast-2.amazonaws.com/frontend-ecr
  newName: 822837196792.dkr.ecr.ap-northeast-2.amazonaws.com/frontend-ecr
  newTag: 33a94c6f
- name: 822837196792.dkr.ecr.ap-northeast-2.amazonaws.com/src-ecr
  newName: 822837196792.dkr.ecr.ap-northeast-2.amazonaws.com/src-ecr
  newTag: 42e1227e
resources:
- ../../base
patchesStrategicMerge:
- front-patch.yaml
